### ISSUE TITLE
Javascript-driven loading screen is obstructive

### ISSUE THREAD

**Issue by Bob131** [natagoh/natagoh.github.io#1]
If the loading screen fails to work as intended (which it may for a plethora of reasons, a few of which I am affected by), you'll end up with people who either wont or can't view your site. Using Javascript to add flashy bits and features is great, but it shouldn't be at the expense of locking out potential visitors.

Just thought I'd let you know

**Comment by natagoh** [comment]
Thanks for the advice Bob131. I've removed the loading animation until I can find a way to make it work on more browsers, os, etc.

**Comment by Bob131** [comment]
No worries, and thank you for the quick response! Site works awesome now :+1:
